stages:
  - build
  - scan

include:
  - project: 'utility/project-templates/ci-templates'
    file: '/docker.yml'

build_backend:
  stage: build
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME
  before_script:
    - echo "Trying to change CI_PROJECT_DIR $CI_PROJECT_DIR ..."
    - export CI_PROJECT_DIR="${CI_PROJECT_DIR}/backend"
    - echo "New value is $CI_PROJECT_DIR"
  extends: .kaniko_build

scan_backend:
  stage: scan
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME
  extends: .docker_scan


