stages:
  - build


include:
  - project: 'utility/project-templates/ci-templates'
    file: '/docker.yml'

build_backend:
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME
    CI_PROJECT_DIR: ${CI_PROJECT_DIR}/backend
  extends: .kaniko_build
