stages:
  - build
  - tag
  - scan

include:
  - project: 'utility/project-templates/ci-templates'
    file: '/docker.yml'

build_backend:
  stage: build
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME
  before_script:
    - export CI_PROJECT_DIR="${CI_PROJECT_DIR}/backend"
    - echo "$CI_PROJECT_DIR"
  extends: .kaniko_build
  only:
    - devel

build_mariadb:
  stage: build
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/mariadb:$CI_COMMIT_REF_NAME
  before_script:
    - export CI_PROJECT_DIR="${CI_PROJECT_DIR}/mariadb"
    - echo "$CI_PROJECT_DIR"
  extends: .kaniko_build
  only:
    - devel

build_redis:
  stage: build
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/redis:$CI_COMMIT_REF_NAME
  before_script:
    - export CI_PROJECT_DIR="${CI_PROJECT_DIR}/redis"
    - echo "$CI_PROJECT_DIR"
  extends: .kaniko_build
  only:
    - devel

tag_backend:
  stage: tag
  variables:
    FROM_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME
    TO_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  extends: .docker_tag
  only:
    - devel

tag_mariadb:
  stage: tag
  variables:
    FROM_IMAGE: ${CI_REGISTRY_IMAGE}/mariadb:$CI_COMMIT_REF_NAME
    TO_IMAGE: ${CI_REGISTRY_IMAGE}/mariadb:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  extends: .docker_tag
  only:
    - devel

tag_redis:
  stage: tag
  variables:
    FROM_IMAGE: ${CI_REGISTRY_IMAGE}/redis:$CI_COMMIT_REF_NAME
    TO_IMAGE: ${CI_REGISTRY_IMAGE}/redis:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  extends: .docker_tag
  only:
    - devel

scan_backend:
  stage: scan
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_REF_NAME
  extends: .docker_scan
  only:
    - devel

scan_mariadb:
  stage: scan
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/mariadb:$CI_COMMIT_REF_NAME
  extends: .docker_scan
  only:
    - devel

scan_redis:
  stage: scan
  variables:
    THE_IMAGE: ${CI_REGISTRY_IMAGE}/redis:$CI_COMMIT_REF_NAME
  extends: .docker_scan
  only:
    - devel
