# This YAML defines the deployment of the Lisberger lab portal application to the Duke OpenShift cluster in the
# braincerebellumdata-test namespace. This namespace is used solely to test and evaluate the application whenever the
# implementation changes in any way (bug fixes, new features, etc).
#
# The application is deployed in a single pod with independent containers for the MariaDB database and the Dash-based
# portal backend running on a GUnicorn WSGI server. Three additional containers in the pod provide a Redis server and
# two Redis Queue workers (that listen to the default queue). The portal backend uses Redis to store information on
# in-progress session commit jobs (so that the backend itself remains stateless), and the RQ workers handle two types of
# background tasks in the workflow for a commit job -- preprocessing of an experiment session archive after upload, and
# pushing session data into the database after the user has reviewed/edited the results from preprocessing.
#
# Since all of the containers are running in a single pod, then the host is really "localhost" or "127.0.0.1". So
# REDIS_HOST=127.0.0.1 (and the same for MARIADB_HOSTNAME!), and the command that starts the RQ worker is "rq worker
# --url redis://127.0.0.0:6379".
#
# NOTES --
#  1) The PVCs listed were created on the Duke OCP console. The PVs are dynamically provisioned.
#  2) The Route resource named 'inbound-route' provides TLS edge termination to the Service sgl-portal-svc, a ClusterIP
#     type service that routes to the GUnicorn-served Dash/Flask backend listening on the node's 8050 port. With this
#     configuration, you access the portal at https://braincerebellumdata-test.ocp.dhe.duke.edu -- BUT you must be on
#     the Duke VPN. We'll want to configure this differently for production.
#
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inbound-route
  labels:
    app: sgl-portal
spec:
  host: braincerebellumdata-test.ocp.dhe.duke.edu
  to:
    kind: Service
    name: portal-server
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: portal-server
  labels:
    app: sgl-portal
    tier: web
spec:
  type: ClusterIP
  selector:
    app: sgl-portal
    tier: web
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: data-store
  labels:
    app: sgl-portal
    tier: data
spec:
  type: ClusterIP
  selector:
    app: sgl-portal
    tier: data
  ports:
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
    - protocol: TCP
      name: mariadb
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-store
  labels:
    app: sgl-portal
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgl-portal
      tier: data
  template:
    metadata:
      labels:
        app: sgl-portal
        tier: data
    spec:
      imagePullSecrets:
      - name: sgl-portal-pull-secret
      containers:
      - name: sgl-db
        image: gitlab.dhe.duke.edu:4567/sar52/sgl-portal/mariadb:devel
        imagePullPolicy: Always
        volumeMounts:
          - name: db-data
            mountPath: /bitnami/mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sgl-secret
                key: mariadb_root_password
        ports:
          - containerPort: 3360
      - name: sgl-redis
        image: gitlab.dhe.duke.edu:4567/sar52/sgl-portal/redis:devel
        imagePullPolicy: Always
        ports:
          - containerPort: 6379
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: pvc-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-worker
  labels:
    app: sgl-portal
    tier: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sgl-portal
      tier: worker
  template:
    metadata:
      labels:
        app: sgl-portal
        tier: worker
    spec:
      imagePullSecrets:
      - name: sgl-portal-pull-secret
      containers:
      - name: web-worker
        image: gitlab.dhe.duke.edu:4567/sar52/sgl-portal/backend:devel
        imagePullPolicy: Always
        command: ["rq"]
        args: ["worker", "--url", "redis://$(REDIS_HOST):$(REDIS_PORT)"]
        volumeMounts:
          - name: backend-repo
            mountPath: /repository
        env:
          - name: REDIS_HOST
            value: data-store.braincerebellumdata-test.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: MARIADB_HOSTNAME
            value: data-store.braincerebellumdata-test.svc.cluster.local
          - name: DJDEV_ROOT_REPO
            value: /repository
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sgl-secret
                key: mariadb_root_password
          - name: FLASK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sgl-secret
                key: flask_secret_key
      volumes:
        - name: backend-repo
          persistentVolumeClaim:
            claimName: pvc-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: sgl-portal
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sgl-portal
      tier: web
  template:
    metadata:
      labels:
        app: sgl-portal
        tier: web
    spec:
      imagePullSecrets:
      - name: sgl-portal-pull-secret
      containers:
      - name: web-server
        image: gitlab.dhe.duke.edu:4567/sar52/sgl-portal/backend:devel
        imagePullPolicy: Always
        ports:
          - containerPort: 8050
        volumeMounts:
          - name: backend-repo
            mountPath: /repository
        env:
          - name: REDIS_HOST
            value: data-store.braincerebellumdata-test.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: MARIADB_HOSTNAME
            value: data-store.braincerebellumdata-test.svc.cluster.local
          - name: DJDEV_ROOT_REPO
            value: /repository
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sgl-secret
                key: mariadb_root_password
          - name: FLASK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sgl-secret
                key: flask_secret_key
      volumes:
        - name: backend-repo
          persistentVolumeClaim:
            claimName: pvc-backend
