# setup.cfg for the sglportalapi clientside package. To build, open Terminal and cd to the project directory .../djdev,
# then run venv3.9/bin/python -m build

[metadata]
name = sglportalapi
author = Scott A. Ruffner
author_email = sruffner@srscicomp.com
version = 0.2.0
description = Clientside access to Lisberger lab portal API endpoints
long_description = file: backend/src/sglportalapi/dist/README.md, backend/src/sglportalapi/dist/CHANGELOG.md
long_description_content_type = text/markdown
license = MIT License
license_files = LICENSE
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python :: 3
    Intended Audience :: End Users/Desktop
    Intended Audience :: Science/Research
    License :: OSI Approved :: MIT License
    Natural Language :: English
    Operating System :: OS Independent
    Programming Language :: Python :: 3.9
    Topic :: Scientific/Engineering :: Information Analysis

[options]
zip_safe = False
package_dir =
    = backend/src
packages =
    sglportalapi
python_requires = >=3.9
install_requires =
    requests >= 2.27.1
    numpy >= 1.22.3
