"""
app_logging.py: Application-specific logging configuration.

The Lisberger lab portal application -- whether deployed as a Docker-Compose application running locally on a
development workstation or as a distributed application on a Kubenetes cluster -- consists of multiple containers,
with multiple processes possibly running within some containers. Each backend container runs the portal application,
with a GUnicorn "master process" managing 5 independent "workers", each of which is an instance of the Flask app. Each
RQ worker container runs a worker process that forks a "workhorse process" that in turn handles a background task
previously queued by the backend. The Flask app instances and any running background task will log messages that are
specific to the portal application. We need to capture these log messages and attach enough information so that the
application log will help investigate bugs and other issues when they occur.

To that end, we decided to create a single Python logger for application-specific logging (versus logs generated by
other participating components like the MariaDB daemon and the Redis server). The logging configuration for this logger
-- named 'portal' -- is defined in config/logging.yaml. That configuration refers to a custom formatter and a custom
handler defined in this file.

The custom formatter tags each emitted log record with the name of the running container (obtained from application
configuration) and the process ID. That way we can better identify the source of each record in this multi-container,
multi-process application.

Two handlers are attached to the 'portal' logger, a StreamHandler that delivers all log records to STDOUT and a custom
handler that logs to file. The StreamHandler is important for aggregating log messages in both the Docker-Compose test
environment and when the application is deployed to Duke's OpenShift cluster. However, we have found that it is rather
difficult to view the aggregated log messages in the latter case. You have to switch among the various pods comprising
the distributed application, when it would be more helpful to see all the log messages in one place -- as they appear on
the console in the Docker-Compose deployment. Another issue with the OpenShift deploymnent is that pods are occasionally
evicted for whatever reason, and when that happens the associated logs are lost.

Therefore, we decided to add a custom file handler that writes all 'portal' logger records to a file in the portal
workspace directory at /logs/appmessages.log. However, the log records will be emitted by multiple processes (5 GUnicorn
workers, and any RQ workhorse process forked to handle a queued background task). This could lead to overlapping writes
that will garble the messages written to the file. Our solution is to post the messages to a single LIST key on the
Redis server. That server is single-threaded, so the log messages won't be garbled (although they may not end up in
chronological order). Basically, we cache log messages to Redis and every once in a while flush the cache to the log
file. The flush operation is handled by queuing a background task to do the work. That task pulls the oldest N messages
from Redis and appends them to the log file. Furthermore, once that file surpasses a certain size, it is renamed as
'appmessages.log-<TS>', where <TS> is a timestamp in the form 'YYYYMonDD-HH.MM', then pushed into the portal repository
in S3 under the /logs prefix. Thus, if the portal crashes, the most recent log messages should be found in the
portal workspace volume at /logs/appmessages.log, while older log messages will be found in the datetime-stamped files
in the portal repository in S3.

@created: apr2022
@author: sruffner
"""
import logging
import logging.config
import time
from datetime import datetime
from pathlib import Path
from random import random
from threading import Thread
from typing import Optional, List

import yaml
from redis import RedisError
from rq import Queue

import config.config
import database.repo
from sglportalapi.util import KB

_LOG_CFG_FILE = 'config/logging.yaml'


def get_application_logger() -> logging.Logger:
    """
    Get the singleton logger used to emit all logs from application code in the portal server app. On the first call,
    application-side logger is configured, along with the root logger. The root logger is configured only to emit logs
    at "WARNING" level and above -- so that we don't get too much crap from third-party libraries. The logging
    configuration is in config/logging.yaml and uses a custom formatter and handler defined in this module.

    Returns:
        The logger to use in all portal server application code.
    Raises:
        RuntimeError: If unable to configure the application-wide logger on first invocation.
    """
    if not ('portal' in logging.root.manager.loggerDict):
        try:
            with open(_LOG_CFG_FILE, 'rt') as f:
                dict_config = yaml.safe_load(f.read())
            logging.config.dictConfig(dict_config)
            if not ('portal' in logging.root.manager.loggerDict):
                raise Exception('The "portal" logger not found after configuration')
            logger = logging.getLogger('portal')
            logger.info("Application logging started.")
            # _start_log_message_generator_daemon()  # for testing only -- otherwise comment out
        except Exception as e:
            raise RuntimeError(f"Failed to create application-wide logger for portal server: {str(e)}")

    return logging.getLogger('portal')


def _start_log_message_generator_daemon():
    """ For testing purposes only: Start a daemon thread that generates an INFO-level log message every 5-10 sec. """
    def _log_frequently():
        logger = get_application_logger()
        while True:
            time.sleep(5.0 + 5.0 * random())
            logger.info("Message from daemon thread testing logging facility")

    t = Thread(name='daemon', target=_log_frequently)
    t.setDaemon(True)
    t.start()


def custom_application_log_formatter() -> logging.Formatter:
    """
    Factory method returns a custom formatter for the application log. The formatter includes the name of the
    running container as obtained from application configuration, process ID, timestamp, function, module, line number,
    log level and message.
    """
    cfg = config.config.get_config()
    return logging.Formatter(fmt=f"{cfg.app_container_name} (PID=%(process)d) | %(asctime)s | "
                                 f"%(funcName)s in %(module)s @ %(lineno)d | %(levelname)s - %(message)s")


def custom_file_handler() -> logging.Handler:
    """
    Factory method returns custom logging handler which safely aggregates log messages from multiple Flask backend
    processes and RQ worker processes by pushing each message onto a Redis LIST key and, once the list exceeds a set
    limit N, queues a background task to trim the oldest N messages from the list and write them to a file in the
    portal workspace. If that file exceeds a set size, it will truncate the file to 0 after backing it up in the portal
    repository in S3.
    """
    return _RedisLogBackupHandler()


_APPMSGLOG_DIR_NAME: str = 'logs'
""" The logs directory in the portal workspace directory."""
_APPMSGLOG_FILE_NAME: str = 'appmessages.log'
""" The application log file. """
_APPMSGLOG_BUF_KEY: str = 'applogbuf'
""" Redis LIST key in which application log messages (coming from multiple processes and containers) are cached. """
_APPMSGLOG_FLUSH_KEY: str = 'applogflush'
""" Redis STRING key exists for 30 seconds after a background task is queued to flush the log message cache to file. """
_APPMSGLOG_FLUSH_LIMIT: int = 50
""" Application log message cache is flushed to the log file whenever it exceeds this size. """
_APPMSGLOG_FILE_SIZE_LIMIT: int = 100*KB
""" 
The application log file in portal workspace is backed up to the portal repository and then truncated to 0 whenever
it exceeds this file size in bytes.
"""


class _RedisLogBackupHandler(logging.Handler):
    """
    Custom handler that caches incoming log messages to a dedicated Redis key, occasionally queueing a background
    task in RQ to flush the log message cache to a file in the portal workspace directory and, when that file grows too
    large, truncate it to 0 after backing it up in the S3-based portal repository.
    """
    def __init__(self):
        logging.Handler.__init__(self, level=logging.INFO)
        self.formatter = custom_application_log_formatter()
        """ The handler's customized formatter. """
        self.redis_conn = config.config.get_config().redis_conn
        """ Connection to the Redis server. """

    def emit(self, record: logging.LogRecord) -> None:
        try:
            n = self.redis_conn.rpush(_APPMSGLOG_BUF_KEY, self.format(record))
            if isinstance(n, int) and (n > _APPMSGLOG_FLUSH_LIMIT):
                if self.redis_conn.set(_APPMSGLOG_FLUSH_KEY, 'pending', ex=30, nx=True):
                    job_queue = Queue(connection=self.redis_conn)
                    job_queue.enqueue(flush_application_message_log_cache, job_id=f"flush-app-log-messages")
        except RedisError:
            get_application_logger().debug(f"Exception on emitting log record", exc_info=True)


def flush_application_message_log_cache() -> bool:
    """
    Flush up to _APPMSGLOG_FLUSH_LIMIT application log messages from the dedicated Redis key _APPMSGLOG_BUF_KEY to the
    application log file in the portal workspace directory. If that file exceeds _APPMSGLOG_FILE_SIZE_LIMIT bytes,
    it is truncated to 0 bytes after backing up its content to file in the portal repository on S3.

    This method is intended ONLY to be called in a background process via RQ.

    Returns:
        True if successful; else False.
    """
    logger = get_application_logger()
    try:
        cfg = config.config.get_config()
        conn = cfg.redis_conn
        messages = conn.lrange(_APPMSGLOG_BUF_KEY, start=0, end=_APPMSGLOG_FLUSH_LIMIT-1)
        conn.ltrim(_APPMSGLOG_BUF_KEY, start=len(messages), end=-1)
        log_path = Path(cfg.workspace_dir, _APPMSGLOG_DIR_NAME, _APPMSGLOG_FILE_NAME)
        if len(messages) > 0:
            with open(log_path, 'a+') as f:
                f.write(f"Flushing {len(messages)} cached messages to application log...\r\n")
                for message in messages:
                    f.write(f"{message.decode()}\r\n")
            logger.info(f"Flushed {len(messages)} application log messages to file")
            if log_path.stat().st_size > _APPMSGLOG_FILE_SIZE_LIMIT:
                now = datetime.now()
                save_path = Path(cfg.workspace_dir, _APPMSGLOG_DIR_NAME,
                                 f"{_APPMSGLOG_FILE_NAME}-{now.strftime('%Y%b%d-%H.%M')}")
                log_path.rename(save_path)
                save_key = f"/{_APPMSGLOG_DIR_NAME}/{save_path.name}"
                if database.repo.upload_file(save_path, save_key):
                    logger.info(f"Backed up application message log to repository at {save_key}")
                    save_path.unlink(missing_ok=True)
        return True
    except Exception:
        logger.error(f"Failed to flush application messages to log file", exc_info=True)
        return False


def force_flush_application_message_log() -> None:
    """
    Flush all application log messages from the Redis key _APPMSGLOG_BUF_KEY to the application log file in the portal
    workspace directory.

    This method is intended to be called in a signal handler when the GUnicorn-served backend is about to exit, so that
    the latest log messages (which might capture an error that has led to the termination) are hopefully preserved in
    the log file for later examination. In addition, if that log file has grown large enough, an attempt is made to
    back it up to S3.

    When this method is called it is possible that a Redis background task is currently performing a periodic flush, or
    even that the Redis server has gone down, so that the application log cache is no longer available. In these
    scenarios, the method will at least try to write a message directly into the log file indicating the error.
    """
    cfg = config.config.get_config()
    messages: Optional[List] = None
    err_msg = None
    try:
        conn = cfg.redis_conn
        if conn.set(_APPMSGLOG_FLUSH_KEY, 'pending', ex=30, nx=True):
            messages = conn.lrange(_APPMSGLOG_BUF_KEY, start=0, end=-1)
            conn.ltrim(_APPMSGLOG_BUF_KEY, start=0, end=-1)
        else:
            err_msg = "Flush operation already pending"
    except RedisError as e:
        err_msg = f"Failed to retrieve application log message cache contents from Redis server: {str(e)}"

    log_path = Path(cfg.workspace_dir, _APPMSGLOG_DIR_NAME, _APPMSGLOG_FILE_NAME)
    try:
        with open(log_path, 'a+') as f:
            if err_msg:
                f.write(f"Application log cache flush operation failed: {err_msg}\r\n")
            elif messages and (len(messages) > 0):
                f.write(f"Flushing {len(messages)} cached messages to application log...\r\n")
                for message in messages:
                    f.write(f"{message.decode()}\r\n")

        if log_path.stat().st_size > _APPMSGLOG_FILE_SIZE_LIMIT:
            now = datetime.now()
            save_path = Path(cfg.workspace_dir, _APPMSGLOG_DIR_NAME,
                             f"{_APPMSGLOG_FILE_NAME}-{now.strftime('%Y%b%d-%H.%M')}")
            log_path.rename(save_path)
            save_key = f"/{_APPMSGLOG_DIR_NAME}/{save_path.name}"
            if database.repo.upload_file(save_path, save_key):
                save_path.unlink(missing_ok=True)
    except Exception:
        pass


def list_application_message_logs() -> List[str]:
    """
    Get a list of application message log names. The list will always include "Recent", which refers to the latest
    messages cached in Redis or flushed to the current log file in the portal server workspace directory. Older log
    files are backed up in the portal repository on S3 and named by a datetime string (eg, '19Apr2022-22.58') indicating
    approximately when the log file was moved to S3.

    Returns:
        List of existing application message log names, as described, in reverse chronological order, with the "Recent"
            entry first.
    """
    out = ["Recent"]
    repo_listing = database.repo.listing()
    log_dir = f"/{_APPMSGLOG_DIR_NAME}"
    msg_log_prefix = f"{_APPMSGLOG_FILE_NAME}-"  # what follows this prefix is a datetime string '%Y%b%d-%H.%M'
    if log_dir in repo_listing:
        for key in repo_listing[log_dir]:
            if key['name'].startswith(msg_log_prefix):
                out.append(key['name'][len(msg_log_prefix):])
    # NOTE: list is already sorted b/c the repo file listing is in reverse chronological order already
    return out


def get_message_log_contents(log_name: str) -> str:
    """
    Retrieve the contents of the application message log specified.

    Args:
        log_name: Name of the application message log to retrieve -- one of the log names returned by the method
            list_application_message_logs().

    Returns:
        Content of the specified application message log. If an error occurs or log was not found, an appropriate
            error message is returned instead.
    """
    if log_name == 'Recent':
        try:
            cfg = config.config.get_config()
            log_path = Path(cfg.workspace_dir, _APPMSGLOG_DIR_NAME, _APPMSGLOG_FILE_NAME)
            if log_path.is_file():
                with open(log_path, 'r') as f:
                    contents = f.read()
            else:
                contents = ""
            messages = cfg.redis_conn.lrange(_APPMSGLOG_BUF_KEY, start=0, end=-1)
            if isinstance(messages, list) and (len(messages) > 0):
                contents += "\r\n".join([msg.decode() for msg in messages])
            return contents
        except Exception:
            get_application_logger().error("Failed to retrieve current application message log", exc_info=True)
            return "An error occurred while retrieving most recent application message log"
    else:
        log_file_key = f"/{_APPMSGLOG_DIR_NAME}/{_APPMSGLOG_FILE_NAME}-{log_name}"
        contents = database.repo.read_text_file(log_file_key)
        if contents is None:
            return "Log file not found, or unable to retrieve it from portal repository"
        else:
            return contents


def delete_application_message_log(log_name: str) -> bool:
    """
    Permanently delete an application message log from the portal repository.

    Args:
        log_name: Name of the application message log to be deleted -- one of the log names returned by the method
            list_application_message_logs() -- other than 'Recent', which cannot be deleted
    Returns:
        True if successful; False otherwise.
    """
    return database.repo.delete_file(f"/{_APPMSGLOG_DIR_NAME}/{_APPMSGLOG_FILE_NAME}-{log_name}")
