# This is just a simple Dockerfile so that I can grab Redis image from Docker Hub and cache it in the container
# registry for the sgl-portal Gitlab project. I believe the "user" is set to "redis" in the Redis base image, so no
# need to do it here. Further specialized configurations for our Redis instance could go here?
#
# This file is not needed for the local Docker Compose nor the single-pod Kubernetes deployment of the portal app.
FROM redis:6.2.5-alpine